### PR TITLE
add tabs section to signers in get_inline_signers

### PR DESCRIPTION
**Pull request by casturm**

### CODE REVIEW

**Comment by tcopeland** [comment]
@casturm first, thanks for the PR.  Lots of water under the bridge since it was opened, of course.  I think some of this has been overtaken by events on master - the change in  9728b33 was merged to master from 7833af96 by @arielfox.   I think the signHereTabs (34b5ba7) change still might merge cleanly though, checking...

**Comment by tcopeland** [comment]
OK I separated out 34b5ba7 and that's on master now (https://github.com/jondkinney/docusign_rest/commit/5aa7ef1db13f44df58a4149e373af72b96d6748d).

**Comment by tcopeland** [comment]
For the last change - the pdf upload diff - if you're still interested in that change, perhaps you could open a new commit (or reopen and rebase / squash this one)?   I recognize that that was almost 3 years ago, so, totally understand if you've moved on from this.

**Comment by casturm** [comment]
Yup, moved on.  Thanks for cleaning this up.

**Pull request closed without merging**
