### PR TITLE
add company tabs and date tabs options

### PR DESCRIPTION
**Pull request by scambra**

### CODE REVIEW

**Comment by tcopeland** [comment]
@scambra if I am reading https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/create/#/definitions/envelopeDefinition, the `enableWetSign` option is now a `requireSignOnPaper` option for each recipient.   Does that sound correct to you?

**Comment by scambra** [comment]
No, that's different option, enableWetSign display link to print document and sign on paper, but it's optional, I don't see explanation about requireSignOnPaper but it doesn't seem optional.
I can see enableWetSign in that link, click on Envelopes section, requireSignOnPaper is under inPersonSigner section.

**Comment by tcopeland** [comment]
@scambra you are right, thanks!   OK, I extracted that part of this change into a separate commit and merged it - https://github.com/jondkinney/docusign_rest/commit/8b590196bd9437cf779d12b2b47f98182933a3ad - so that's progress.  Thank you!

I'm having a little trouble sorting out what else is in this PR - maybe it's worth closing this one and you opening a new one that's rebased off master with any additional changes?

**Comment by scambra** [comment]
I can do that, but it may take some days, I'm busy on these days

**Comment by tommotorefi** [comment]
No problem!   Your contributions are welcome, for sure.   OK I will close this then.  Thank you again!

**Comment by tcopeland** [comment]
No problem! Your contributions are welcome, for sure. OK I will close this then. Thank you again!

**Pull request closed without merging**
