### PR TITLE
YT-3288 single signer

### PR DESCRIPTION
**Pull request by pramodtech**

### CODE REVIEW

**Comment by tcopeland** [comment]
@pramodtech thanks for the PR!  It looks like it doesn't currently rebase cleanly... but I might be able to cherry-pick out the relevant commits.  I'll give it a try.

**Comment by tcopeland** [comment]
Cherry picked Ryan's 5d782cd38 fix to void_envelope.

**Comment by tcopeland** [comment]
Tweaked Lakshmi's 3a9bf46e61a a bit and cherry-picked - I don't have an account with signing groups enabled, but it seems like a good change.

**Comment by tcopeland** [comment]
All picked to master.  Thanks again @pramodtech!  I'll look to get a new release of the gem out soon.

**Comment by pramodtech** [comment]
@tcopeland thanks for tweaks and cherry-picks. I being lazy didn't rebase my changes :)

**Comment by tcopeland** [comment]
You bet!  And no worries, thanks for the codes.

**Pull request closed without merging**
